-- chaos_postgres_update.sql
-- 变动日志（增量 DDL）。先应用 chaos_postgres_schema.sql 快照，再按时间顺序应用本文件。
-- chaos_postgres_schema.sql 为手动导出的基准快照，请勿修改；所有结构变动追加到本文件末尾并注明日期与用途。

-- ============================================================
-- 2026-08-04: 新增 SDK 来源表（sdk-version-db 变更）
-- 一行 = 一个 SDK 类型(jdk/maven/python/...)，sources 为该类型下来源 JSON 数组
-- 仓库(repo，父目录下子目录为版本) 与 单个版本(single，一个目录即一个版本) 可混合共存
-- current 存当前启用版本的绝对路径(单值即保证同时仅一个版本启用)
-- 对应模型：internal/proxy.SdkSource
-- ============================================================

CREATE TABLE public.sdk_sources (
    id         integer   NOT NULL,
    name       text      NOT NULL,
    sources    jsonb     NOT NULL,
    current    text,
    enabled    boolean   DEFAULT true,
    note       text,
    is_deleted boolean   DEFAULT false
);
COMMENT ON TABLE public.sdk_sources IS 'SDK 来源表：一行代表一个 SDK 类型(jdk/maven/python/...)，sources 存其来源数组';
COMMENT ON COLUMN public.sdk_sources.name IS 'SDK 类型唯一标识，作 GET /sdks 的 map key 与切换 :name';
COMMENT ON COLUMN public.sdk_sources.sources IS '来源 JSON 数组，元素 {kind:repo|single, root:绝对路径}；repo 与 single 可混合';
COMMENT ON COLUMN public.sdk_sources.current IS '当前启用版本的绝对路径；单值即保证同时仅一个版本启用';
COMMENT ON COLUMN public.sdk_sources.enabled IS '该 SDK 类型是否启用，禁用后不参与版本读取';
COMMENT ON COLUMN public.sdk_sources.note IS '备注';
COMMENT ON COLUMN public.sdk_sources.is_deleted IS '软删除标记';

ALTER TABLE public.sdk_sources ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sdk_sources_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

ALTER TABLE ONLY public.sdk_sources ADD CONSTRAINT sdk_sources_pkey PRIMARY KEY (id);

CREATE UNIQUE INDEX idx_sdk_sources_name ON public.sdk_sources USING btree (name) WHERE (is_deleted = false);

-- ============================================================
-- 2026-09-05: task_plans 新增 raw_link 字段
-- 用于存储由 link 换算出的 chaos-knots raw 接口链接（src→raw 并追加 token），便于直接拉取原文内容。
-- 对应换算逻辑见 chaos-go/cmd/test/test.go 的 UpdateRawLink() / toRawLink()。
-- ============================================================

ALTER TABLE public.task_plans ADD COLUMN IF NOT EXISTS raw_link text;
COMMENT ON COLUMN public.task_plans.raw_link IS '由 link 换算出的 raw 接口链接（src→raw 并追加 token），用于直接拉取原文内容';
