-- chaos_postgres_update.sql
-- 变动日志（增量 DDL）。先应用 chaos_postgres_schema.sql 快照，再按时间顺序应用本文件。
-- chaos_postgres_schema.sql 为手动导出的基准快照，请勿修改；所有结构变动追加到本文件末尾并注明日期与用途。

-- ============================================================
-- 2026-08-04: 新增 SDK 来源表（sdk-version-db 变更）
-- 一行 = 一个 SDK 类型(jdk/maven/python/...)，sources 为该类型下来源 JSON 数组
-- 仓库(repo，父目录下子目录为版本) 与 单个版本(single，一个目录即一个版本) 可混合共存
-- current 存当前启用版本的绝对路径(单值即保证同时仅一个版本启用)
-- 对应模型：internal/proxy.SdkSource
-- ============================================================

CREATE TABLE public.sdk_sources (
    id         integer   NOT NULL,
    name       text      NOT NULL,
    sources    jsonb     NOT NULL,
    current    text,
    enabled    boolean   DEFAULT true,
    note       text,
    is_deleted boolean   DEFAULT false
);
COMMENT ON TABLE public.sdk_sources IS 'SDK 来源表：一行代表一个 SDK 类型(jdk/maven/python/...)，sources 存其来源数组';
COMMENT ON COLUMN public.sdk_sources.name IS 'SDK 类型唯一标识，作 GET /sdks 的 map key 与切换 :name';
COMMENT ON COLUMN public.sdk_sources.sources IS '来源 JSON 数组，元素 {kind:repo|single, root:绝对路径}；repo 与 single 可混合';
COMMENT ON COLUMN public.sdk_sources.current IS '当前启用版本的绝对路径；单值即保证同时仅一个版本启用';
COMMENT ON COLUMN public.sdk_sources.enabled IS '该 SDK 类型是否启用，禁用后不参与版本读取';
COMMENT ON COLUMN public.sdk_sources.note IS '备注';
COMMENT ON COLUMN public.sdk_sources.is_deleted IS '软删除标记';

ALTER TABLE public.sdk_sources ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sdk_sources_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

ALTER TABLE ONLY public.sdk_sources ADD CONSTRAINT sdk_sources_pkey PRIMARY KEY (id);

CREATE UNIQUE INDEX idx_sdk_sources_name ON public.sdk_sources USING btree (name) WHERE (is_deleted = false);

-- ============================================================
-- 2026-09-05: task_plans 新增 raw_link 字段
-- 用于存储由 link 换算出的 chaos-knots raw 接口链接（src→raw 并追加 token），便于直接拉取原文内容。
-- 对应换算逻辑见 chaos-go/cmd/test/test.go 的 UpdateRawLink() / toRawLink()。
-- ============================================================

ALTER TABLE public.task_plans ADD COLUMN IF NOT EXISTS raw_link text;
COMMENT ON COLUMN public.task_plans.raw_link IS '由 link 换算出的 raw 接口链接（src→raw 并追加 token），用于直接拉取原文内容';

-- ============================================================
-- 2026-09-12: SSH 端口转发（ssh-port-forward 变更）
-- 新增 ssh_connections 表保存 SSH 连接信息（密码或私钥）；
-- port_forwarding 增加 ssh_connection_id（关联 SSH 连接）与 remark 列。
-- 凭据列仅后端建立 SSH 隧道时使用：API 一律不回显，日志不记录。
-- 对应模型：internal/portfwd.SshConnection、internal/portfwd.PortForwarding
-- ============================================================

CREATE TABLE public.ssh_connections (
    id          integer NOT NULL,
    name        text,
    host        text,
    port        bigint,
    username    text,
    auth_type   text,
    password    text,
    private_key text,
    passphrase  text,
    remark      text
);
COMMENT ON TABLE public.ssh_connections IS 'SSH 连接信息：端口转发经此连接建立 SSH 隧道（本地转发，等价 ssh -L）';
COMMENT ON COLUMN public.ssh_connections.name IS '连接名称，供选择与展示';
COMMENT ON COLUMN public.ssh_connections.host IS 'SSH 服务器主机';
COMMENT ON COLUMN public.ssh_connections.port IS 'SSH 服务器端口，默认 22';
COMMENT ON COLUMN public.ssh_connections.username IS 'SSH 用户名';
COMMENT ON COLUMN public.ssh_connections.auth_type IS '认证方式：password（密码）/ key（私钥）';
COMMENT ON COLUMN public.ssh_connections.password IS '密码认证的密码；仅后端建连使用，API 不回显、日志不记录';
COMMENT ON COLUMN public.ssh_connections.private_key IS '私钥认证的私钥内容（PEM）；仅后端建连使用，API 不回显、日志不记录';
COMMENT ON COLUMN public.ssh_connections.passphrase IS '私钥口令（可选）；仅后端建连使用，API 不回显、日志不记录';
COMMENT ON COLUMN public.ssh_connections.remark IS '备注';

ALTER TABLE public.ssh_connections ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ssh_connections_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

ALTER TABLE ONLY public.ssh_connections ADD CONSTRAINT ssh_connections_pkey PRIMARY KEY (id);

ALTER TABLE public.port_forwarding ADD COLUMN IF NOT EXISTS ssh_connection_id integer;
ALTER TABLE public.port_forwarding ADD COLUMN IF NOT EXISTS remark text;
COMMENT ON COLUMN public.port_forwarding.ssh_connection_id IS '关联的 SSH 连接 id（ssh_connections.id）';
COMMENT ON COLUMN public.port_forwarding.remark IS '端口转发规则备注';

-- ============================================================
-- 2026-09-12: SSH 远程转发（ssh-remote-forward 变更）
-- port_forwarding 增加 direction 与 bind_address 两列：
--   direction = local：在本机监听（等价 ssh -L），bind_address 缺省 0.0.0.0；
--   direction = remote：在 SSH 服务器侧监听（等价 ssh -R），bind_address 缺省 127.0.0.1。
-- 方向为空的历史数据一律视为 local（本次回填显式化，读路径也做了兜底）。
-- 对应模型：internal/portfwd.PortForwarding
-- ============================================================

ALTER TABLE public.port_forwarding ADD COLUMN IF NOT EXISTS direction text;
ALTER TABLE public.port_forwarding ADD COLUMN IF NOT EXISTS bind_address text;
COMMENT ON COLUMN public.port_forwarding.direction IS '转发方向：local（本机监听，等价 ssh -L）/ remote（SSH 服务器侧监听，等价 ssh -R）；空值视为 local';
COMMENT ON COLUMN public.port_forwarding.bind_address IS '监听地址：local 为本机监听地址（缺省 0.0.0.0），remote 为 SSH 服务器侧监听地址（缺省 127.0.0.1）';

UPDATE public.port_forwarding SET direction = 'local' WHERE direction IS NULL OR direction = '';
