-- chaos_postgres_update.sql
-- 变动日志（增量 DDL）。先应用 chaos_postgres_schema.sql 快照，再按时间顺序应用本文件。
-- chaos_postgres_schema.sql 为手动导出的基准快照，请勿修改；所有结构变动追加到本文件末尾并注明日期与用途。

-- ============================================================
-- 2026-08-04: 新增 SDK 来源表（sdk-version-db 变更）
-- 一行 = 一个 SDK 类型(jdk/maven/python/...)，sources 为该类型下来源 JSON 数组
-- 仓库(repo，父目录下子目录为版本) 与 单个版本(single，一个目录即一个版本) 可混合共存
-- current 存当前启用版本的绝对路径(单值即保证同时仅一个版本启用)
-- 对应模型：internal/proxy.SdkSource
-- ============================================================

CREATE TABLE public.sdk_sources (
    id         integer   NOT NULL,
    name       text      NOT NULL,
    sources    jsonb     NOT NULL,
    current    text,
    enabled    boolean   DEFAULT true,
    note       text,
    is_deleted boolean   DEFAULT false
);
COMMENT ON TABLE public.sdk_sources IS 'SDK 来源表：一行代表一个 SDK 类型(jdk/maven/python/...)，sources 存其来源数组';
COMMENT ON COLUMN public.sdk_sources.name IS 'SDK 类型唯一标识，作 GET /sdks 的 map key 与切换 :name';
COMMENT ON COLUMN public.sdk_sources.sources IS '来源 JSON 数组，元素 {kind:repo|single, root:绝对路径}；repo 与 single 可混合';
COMMENT ON COLUMN public.sdk_sources.current IS '当前启用版本的绝对路径；单值即保证同时仅一个版本启用';
COMMENT ON COLUMN public.sdk_sources.enabled IS '该 SDK 类型是否启用，禁用后不参与版本读取';
COMMENT ON COLUMN public.sdk_sources.note IS '备注';
COMMENT ON COLUMN public.sdk_sources.is_deleted IS '软删除标记';

ALTER TABLE public.sdk_sources ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sdk_sources_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

ALTER TABLE ONLY public.sdk_sources ADD CONSTRAINT sdk_sources_pkey PRIMARY KEY (id);

CREATE UNIQUE INDEX idx_sdk_sources_name ON public.sdk_sources USING btree (name) WHERE (is_deleted = false);

-- ============================================================
-- 2026-09-05: task_plans 新增 raw_link 字段
-- 用于存储由 link 换算出的 chaos-knots raw 接口链接（src→raw 并追加 token），便于直接拉取原文内容。
-- 对应换算逻辑见 chaos-go/cmd/test/test.go 的 UpdateRawLink() / toRawLink()。
-- ============================================================

ALTER TABLE public.task_plans ADD COLUMN IF NOT EXISTS raw_link text;
COMMENT ON COLUMN public.task_plans.raw_link IS '由 link 换算出的 raw 接口链接（src→raw 并追加 token），用于直接拉取原文内容';

-- ============================================================
-- 2026-09-12: SSH 端口转发（ssh-port-forward 变更）
-- 新增 ssh_connections 表保存 SSH 连接信息（密码或私钥）；
-- port_forwarding 增加 ssh_connection_id（关联 SSH 连接）与 remark 列。
-- 凭据列仅后端建立 SSH 隧道时使用：API 一律不回显，日志不记录。
-- 对应模型：internal/portfwd.SshConnection、internal/portfwd.PortForwarding
-- ============================================================

CREATE TABLE public.ssh_connections (
    id          integer NOT NULL,
    name        text,
    host        text,
    port        bigint,
    username    text,
    auth_type   text,
    password    text,
    private_key text,
    passphrase  text,
    remark      text
);
COMMENT ON TABLE public.ssh_connections IS 'SSH 连接信息：端口转发经此连接建立 SSH 隧道（本地转发，等价 ssh -L）';
COMMENT ON COLUMN public.ssh_connections.name IS '连接名称，供选择与展示';
COMMENT ON COLUMN public.ssh_connections.host IS 'SSH 服务器主机';
COMMENT ON COLUMN public.ssh_connections.port IS 'SSH 服务器端口，默认 22';
COMMENT ON COLUMN public.ssh_connections.username IS 'SSH 用户名';
COMMENT ON COLUMN public.ssh_connections.auth_type IS '认证方式：password（密码）/ key（私钥）';
COMMENT ON COLUMN public.ssh_connections.password IS '密码认证的密码；仅后端建连使用，API 不回显、日志不记录';
COMMENT ON COLUMN public.ssh_connections.private_key IS '私钥认证的私钥内容（PEM）；仅后端建连使用，API 不回显、日志不记录';
COMMENT ON COLUMN public.ssh_connections.passphrase IS '私钥口令（可选）；仅后端建连使用，API 不回显、日志不记录';
COMMENT ON COLUMN public.ssh_connections.remark IS '备注';

ALTER TABLE public.ssh_connections ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ssh_connections_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

ALTER TABLE ONLY public.ssh_connections ADD CONSTRAINT ssh_connections_pkey PRIMARY KEY (id);

ALTER TABLE public.port_forwarding ADD COLUMN IF NOT EXISTS ssh_connection_id integer;
ALTER TABLE public.port_forwarding ADD COLUMN IF NOT EXISTS remark text;
COMMENT ON COLUMN public.port_forwarding.ssh_connection_id IS '关联的 SSH 连接 id（ssh_connections.id）';
COMMENT ON COLUMN public.port_forwarding.remark IS '端口转发规则备注';

-- ============================================================
-- 2026-09-12: SSH 远程转发（ssh-remote-forward 变更）
-- port_forwarding 增加 direction 与 bind_address 两列：
--   direction = local：在本机监听（等价 ssh -L），bind_address 缺省 0.0.0.0；
--   direction = remote：在 SSH 服务器侧监听（等价 ssh -R），bind_address 缺省 127.0.0.1。
-- 方向为空的历史数据一律视为 local（本次回填显式化，读路径也做了兜底）。
-- 对应模型：internal/portfwd.PortForwarding
-- ============================================================

ALTER TABLE public.port_forwarding ADD COLUMN IF NOT EXISTS direction text;
ALTER TABLE public.port_forwarding ADD COLUMN IF NOT EXISTS bind_address text;
COMMENT ON COLUMN public.port_forwarding.direction IS '转发方向：local（本机监听，等价 ssh -L）/ remote（SSH 服务器侧监听，等价 ssh -R）；空值视为 local';
COMMENT ON COLUMN public.port_forwarding.bind_address IS '监听地址：local 为本机监听地址（缺省 0.0.0.0），remote 为 SSH 服务器侧监听地址（缺省 127.0.0.1）';

UPDATE public.port_forwarding SET direction = 'local' WHERE direction IS NULL OR direction = '';

-- ============================================================
-- 2026-09-15: 直接转发（direct 方向）
-- port_forwarding.direction 新增取值 direct：
--   直接转发 = 本机监听（监听地址缺省 0.0.0.0），接入流量经纯 TCP 直连目标（host:port），不经 SSH 隧道；
--   因此 direct 规则不关联 ssh_connection_id（无对应连接时本列存 0），其余字段含义与 local 一致。
-- 列结构无需变更（direction 已是 text），此处仅补充取值说明，便于人工维护。
-- 对应模型：internal/portfwd.PortForwarding
-- ============================================================

COMMENT ON COLUMN public.port_forwarding.direction IS '转发方向：local（本机监听，等价 ssh -L）/ remote（SSH 服务器侧监听，等价 ssh -R）/ direct（本机监听直连目标，纯 TCP，不经 SSH）；空值视为 local';


-- ============================================================
-- 2026-09-13: MQTT 多节点消息同步（mqtt-cluster-sync 变更）
-- 新增 mqtt_sync_messages（订阅/发布落库的消息，payload 明文）与 mqtt_sync_node（本机节点标识）。
-- 界面仅展示每个 channel 最新一条（按 MAX(id) 取），旧消息全部保留。
-- 对应模型：internal/mqttsync.MqttSyncMessage、internal/mqttsync.MqttSyncNode
-- ============================================================

CREATE TABLE public.mqtt_sync_messages (
    id          integer   NOT NULL,
    msg_id      text      NOT NULL,
    node_id     text,
    channel     text,
    payload     text,
    created_at  timestamp,
    is_deleted  boolean   DEFAULT false
);
COMMENT ON TABLE public.mqtt_sync_messages IS 'MQTT 多节点同步消息落库表：每个 channel 仅界面展示最新一条，旧消息保留';
COMMENT ON COLUMN public.mqtt_sync_messages.msg_id IS '线上报文 id（uuid），全局唯一，用于去重';
COMMENT ON COLUMN public.mqtt_sync_messages.node_id IS '发送方节点标识';
COMMENT ON COLUMN public.mqtt_sync_messages.channel IS 'topic（不含前缀），如 broadcast';
COMMENT ON COLUMN public.mqtt_sync_messages.payload IS '消息内容（本期明文，加密为后续变更）';
COMMENT ON COLUMN public.mqtt_sync_messages.is_deleted IS '软删除标记';

ALTER TABLE public.mqtt_sync_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mqtt_sync_messages_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

ALTER TABLE ONLY public.mqtt_sync_messages ADD CONSTRAINT mqtt_sync_messages_pkey PRIMARY KEY (id);
CREATE UNIQUE INDEX idx_mqtt_sync_messages_msg_id ON public.mqtt_sync_messages USING btree (msg_id) WHERE (is_deleted = false);

CREATE TABLE public.mqtt_sync_node (
    id          integer   NOT NULL,
    node_id     text      NOT NULL,
    created_at  timestamp
);
COMMENT ON TABLE public.mqtt_sync_node IS '本机节点标识：首次启动生成并持久化，全程稳定';
COMMENT ON COLUMN public.mqtt_sync_node.node_id IS '节点唯一标识（uuid），用作回声丢弃与界面「本机」标识';

ALTER TABLE public.mqtt_sync_node ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mqtt_sync_node_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

ALTER TABLE ONLY public.mqtt_sync_node ADD CONSTRAINT mqtt_sync_node_pkey PRIMARY KEY (id);
CREATE UNIQUE INDEX idx_mqtt_sync_node_node_id ON public.mqtt_sync_node USING btree (node_id);

-- ============================================================
-- 2026-09-19: 常用书签独立实现（frequent-bookmarks 变更）
-- 新增 bookmarks 表，由扩展周期性备份浏览器书签树（扁平快照）；
-- 常用书签 = bookmarks 关联 browser_histories 的访问次数，按访问频率降序分页返回（默认 20）。
-- 对应模型：internal/proxy.Bookmark；接口 GET /frequentBookmarks、POST /bookmarks
-- ============================================================

CREATE TABLE public.bookmarks (
    id         text    NOT NULL,
    parent_id  text,
    title      text,
    url        text,
    is_folder  boolean DEFAULT false,
    sort_index integer DEFAULT 0,
    date_added bigint
);
COMMENT ON TABLE public.bookmarks IS '浏览器书签扁平快照：由扩展周期备份；url 非空为书签叶子，空为文件夹';
COMMENT ON COLUMN public.bookmarks.id IS '浏览器书签节点原始 id（稳定唯一）';
COMMENT ON COLUMN public.bookmarks.parent_id IS '父文件夹 id';
COMMENT ON COLUMN public.bookmarks.title IS '书签/文件夹标题';
COMMENT ON COLUMN public.bookmarks.url IS '书签 URL；文件夹为空';
COMMENT ON COLUMN public.bookmarks.is_folder IS '是否为文件夹';
COMMENT ON COLUMN public.bookmarks.sort_index IS '同级中的顺序';
COMMENT ON COLUMN public.bookmarks.date_added IS '书签创建时间戳（毫秒）';

ALTER TABLE ONLY public.bookmarks ADD CONSTRAINT bookmarks_pkey PRIMARY KEY (id);
CREATE INDEX idx_bookmarks_url ON public.bookmarks USING btree (url) WHERE (url <> '');

-- 文件连接接入标准 CRUD 基线（模型嵌入 crud.BaseModel）：补创建/更新时间
ALTER TABLE public.file_links ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE public.file_links ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
