--
-- PostgreSQL database dump
--

\restrict 7zkAqOBN5nWzKZNku8wrVuaRht8krfICyEZoTfxQscsEcEhcesyqtKlfxDoyxRW

-- Dumped from database version 17.10 (Debian 17.10-1.pgdg12+1)
-- Dumped by pg_dump version 17.10 (Debian 17.10-1.pgdg12+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: browser_histories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.browser_histories (
    id character varying NOT NULL,
    last_visit_time numeric,
    title text,
    type_count bigint,
    url text,
    visit_count bigint,
    is_deleted boolean DEFAULT false
);


ALTER TABLE public.browser_histories OWNER TO postgres;

--
-- Name: browser_history_visits; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.browser_history_visits (
    id character varying NOT NULL,
    history_id text,
    is_local boolean,
    referring_visit_id text,
    transition text,
    visit_id text,
    visit_time numeric,
    is_deleted boolean DEFAULT false
);


ALTER TABLE public.browser_history_visits OWNER TO postgres;

--
-- Name: file_links; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.file_links (
    id integer NOT NULL,
    source_path text,
    target_path text,
    status boolean,
    remark text,
    is_deleted boolean DEFAULT false
);


ALTER TABLE public.file_links OWNER TO postgres;

--
-- Name: file_link_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.file_links ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.file_link_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: port_forwarding; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.port_forwarding (
    id integer NOT NULL,
    name text,
    port bigint,
    target_host text,
    target_port bigint,
    status boolean,
    is_deleted boolean DEFAULT false
);


ALTER TABLE public.port_forwarding OWNER TO postgres;

--
-- Name: port_forwarding_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.port_forwarding ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.port_forwarding_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: project_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.project_groups (
    id integer NOT NULL,
    name text,
    absolute_path text,
    remark text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    is_deleted boolean DEFAULT false,
    order_num bigint DEFAULT 0,
    is_recycle_bin boolean DEFAULT false
);


ALTER TABLE public.project_groups OWNER TO postgres;

--
-- Name: TABLE project_groups; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.project_groups IS '项目组表';


--
-- Name: COLUMN project_groups.id; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.project_groups.id IS '项目组唯一标识';


--
-- Name: COLUMN project_groups.name; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.project_groups.name IS '项目组名称';


--
-- Name: COLUMN project_groups.absolute_path; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.project_groups.absolute_path IS '项目组根目录绝对路径，其下项目通过相对路径定位';


--
-- Name: COLUMN project_groups.remark; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.project_groups.remark IS '备注';


--
-- Name: COLUMN project_groups.created_at; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.project_groups.created_at IS '创建时间';


--
-- Name: COLUMN project_groups.updated_at; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.project_groups.updated_at IS '更新时间';


--
-- Name: COLUMN project_groups.order_num; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.project_groups.order_num IS '排序序号，越小越靠前';


--
-- Name: project_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.project_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.project_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: projects; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.projects (
    id integer NOT NULL,
    group_id bigint,
    name text,
    absolute_path text,
    relative_path text,
    git_url text,
    remark text,
    last_accessed_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    is_deleted boolean DEFAULT false
);


ALTER TABLE public.projects OWNER TO postgres;

--
-- Name: TABLE projects; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.projects IS '项目表';


--
-- Name: COLUMN projects.id; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.projects.id IS '项目唯一标识';


--
-- Name: COLUMN projects.group_id; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.projects.group_id IS '所属项目组ID';


--
-- Name: COLUMN projects.name; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.projects.name IS '项目名称';


--
-- Name: COLUMN projects.absolute_path; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.projects.absolute_path IS '项目绝对路径，等于 组绝对路径 + 相对路径';


--
-- Name: COLUMN projects.relative_path; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.projects.relative_path IS '相对所属项目组根目录的路径';


--
-- Name: COLUMN projects.git_url; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.projects.git_url IS 'Git 仓库地址';


--
-- Name: COLUMN projects.remark; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.projects.remark IS '备注';


--
-- Name: COLUMN projects.last_accessed_at; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.projects.last_accessed_at IS '上次访问时间';


--
-- Name: COLUMN projects.created_at; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.projects.created_at IS '创建时间';


--
-- Name: COLUMN projects.updated_at; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.projects.updated_at IS '更新时间';


--
-- Name: projects_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.projects ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.projects_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: quick_edit_files; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.quick_edit_files (
    id integer NOT NULL,
    name text,
    file_path text,
    remark text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    is_deleted boolean DEFAULT false
);


ALTER TABLE public.quick_edit_files OWNER TO postgres;

--
-- Name: quick_edit_files_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.quick_edit_files ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quick_edit_files_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: quick_edit_snapshots; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.quick_edit_snapshots (
    id integer NOT NULL,
    file_id bigint,
    content text,
    size_bytes bigint,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    is_deleted boolean DEFAULT false
);


ALTER TABLE public.quick_edit_snapshots OWNER TO postgres;

--
-- Name: quick_edit_snapshots_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.quick_edit_snapshots ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quick_edit_snapshots_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: task_plan_old; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.task_plan_old (
    id character varying(36) NOT NULL,
    pid character varying(36) NOT NULL,
    name character varying(100) NOT NULL,
    code character varying(100) NOT NULL,
    type character varying(32) DEFAULT 'DEFAULT'::character varying NOT NULL,
    priority integer DEFAULT 0 NOT NULL,
    remarks text,
    sort_code integer DEFAULT 0 NOT NULL,
    start_time timestamp without time zone,
    end_time timestamp without time zone,
    status character varying(32) DEFAULT 'DEFAULT'::character varying NOT NULL,
    complete_time timestamp without time zone,
    url_link character varying(512),
    create_by character varying(36),
    update_by character varying(36),
    create_date timestamp without time zone,
    update_date timestamp without time zone,
    data_status integer DEFAULT 0 NOT NULL,
    proficiency integer DEFAULT 0 NOT NULL,
    last_review_time timestamp without time zone,
    review_record text
);


ALTER TABLE public.task_plan_old OWNER TO postgres;

--
-- Name: TABLE task_plan_old; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.task_plan_old IS '任务计划';


--
-- Name: COLUMN task_plan_old.id; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.task_plan_old.id IS '主键';


--
-- Name: COLUMN task_plan_old.pid; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.task_plan_old.pid IS '父ID';


--
-- Name: COLUMN task_plan_old.name; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.task_plan_old.name IS '名称';


--
-- Name: COLUMN task_plan_old.code; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.task_plan_old.code IS '编码';


--
-- Name: COLUMN task_plan_old.type; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.task_plan_old.type IS '类型';


--
-- Name: COLUMN task_plan_old.priority; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.task_plan_old.priority IS '优先级';


--
-- Name: COLUMN task_plan_old.remarks; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.task_plan_old.remarks IS '备注';


--
-- Name: COLUMN task_plan_old.sort_code; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.task_plan_old.sort_code IS '排序';


--
-- Name: COLUMN task_plan_old.start_time; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.task_plan_old.start_time IS '开始时间';


--
-- Name: COLUMN task_plan_old.end_time; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.task_plan_old.end_time IS '结束时间';


--
-- Name: COLUMN task_plan_old.status; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.task_plan_old.status IS '状态';


--
-- Name: COLUMN task_plan_old.complete_time; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.task_plan_old.complete_time IS '完成时间';


--
-- Name: COLUMN task_plan_old.url_link; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.task_plan_old.url_link IS '链接';


--
-- Name: COLUMN task_plan_old.create_by; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.task_plan_old.create_by IS '创建人';


--
-- Name: COLUMN task_plan_old.update_by; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.task_plan_old.update_by IS '更新人';


--
-- Name: COLUMN task_plan_old.create_date; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.task_plan_old.create_date IS '创建时间';


--
-- Name: COLUMN task_plan_old.update_date; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.task_plan_old.update_date IS '更新时间';


--
-- Name: COLUMN task_plan_old.data_status; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.task_plan_old.data_status IS '数据状态';


--
-- Name: COLUMN task_plan_old.proficiency; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.task_plan_old.proficiency IS '熟练度';


--
-- Name: COLUMN task_plan_old.last_review_time; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.task_plan_old.last_review_time IS '上次复习时间';


--
-- Name: COLUMN task_plan_old.review_record; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.task_plan_old.review_record IS '复习记录';


--
-- Name: task_plans; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.task_plans (
    id integer NOT NULL,
    parent_id bigint,
    name text,
    status text DEFAULT 'created'::character varying,
    plan_type text DEFAULT 'todo'::character varying,
    cron_expr text,
    fsrs_stability numeric DEFAULT 0,
    fsrs_difficulty numeric DEFAULT 0,
    fsrs_reps bigint DEFAULT 0,
    fsrs_lapses bigint DEFAULT 0,
    fsrs_last_review_at timestamp with time zone,
    remark text,
    link text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    is_deleted boolean DEFAULT false,
    order_num integer DEFAULT 0,
    priority integer DEFAULT 5,
    fsrs_state integer DEFAULT 0,
    fsrs_learning_steps integer DEFAULT 0,
    content_size integer DEFAULT 0,
    is_suspended boolean DEFAULT false
);


ALTER TABLE public.task_plans OWNER TO postgres;

--
-- Name: TABLE task_plans; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.task_plans IS '任务计划表';


--
-- Name: COLUMN task_plans.id; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.task_plans.id IS '任务计划唯一标识';


--
-- Name: COLUMN task_plans.parent_id; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.task_plans.parent_id IS '父级任务计划ID，用于树形目录结构。NULL 表示顶级目录';


--
-- Name: COLUMN task_plans.name; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.task_plans.name IS '任务计划名称';


--
-- Name: COLUMN task_plans.status; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.task_plans.status IS '任务计划状态: created(已创建) / started(已开始) / completed(已完成) / archived(已归档)';


--
-- Name: COLUMN task_plans.plan_type; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.task_plans.plan_type IS '任务类型: todo(待办任务) / cron(周期重复任务) / interval(间隔任务)';


--
-- Name: COLUMN task_plans.cron_expr; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.task_plans.cron_expr IS 'cron: cron 表达式，plan_type=cron 时必填';


--
-- Name: COLUMN task_plans.fsrs_stability; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.task_plans.fsrs_stability IS 'fsrs: 记忆稳定性，plan_type=interval 时使用';


--
-- Name: COLUMN task_plans.fsrs_difficulty; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.task_plans.fsrs_difficulty IS 'fsrs: 卡片难度，plan_type=interval 时使用';


--
-- Name: COLUMN task_plans.fsrs_reps; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.task_plans.fsrs_reps IS 'fsrs: 复习次数，plan_type=interval 时使用';


--
-- Name: COLUMN task_plans.fsrs_lapses; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.task_plans.fsrs_lapses IS 'fsrs: 遗忘次数，plan_type=interval 时使用';


--
-- Name: COLUMN task_plans.fsrs_last_review_at; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.task_plans.fsrs_last_review_at IS 'fsrs: 上次复习时间，plan_type=interval 时使用';


--
-- Name: COLUMN task_plans.remark; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.task_plans.remark IS '备注';


--
-- Name: COLUMN task_plans.link; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.task_plans.link IS '关联链接';


--
-- Name: COLUMN task_plans.created_at; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.task_plans.created_at IS '创建时间';


--
-- Name: COLUMN task_plans.updated_at; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.task_plans.updated_at IS '更新时间';


--
-- Name: task_plans_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.task_plans ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.task_plans_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tasks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tasks (
    id integer NOT NULL,
    plan_id bigint,
    status text DEFAULT 'active'::character varying,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    deadline timestamp with time zone,
    remark text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    is_deleted boolean DEFAULT false,
    priority integer DEFAULT 5
);


ALTER TABLE public.tasks OWNER TO postgres;

--
-- Name: TABLE tasks; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.tasks IS '任务表（每次执行的实例记录）';


--
-- Name: COLUMN tasks.id; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.tasks.id IS '任务唯一标识';


--
-- Name: COLUMN tasks.plan_id; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.tasks.plan_id IS '所属任务计划ID';


--
-- Name: COLUMN tasks.status; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.tasks.status IS '任务状态: active(已开始/待处理) / done(已完成)';


--
-- Name: COLUMN tasks.started_at; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.tasks.started_at IS '任务开始时间（cron/间隔任务的计算时间，待办任务为创建时间）';


--
-- Name: COLUMN tasks.completed_at; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.tasks.completed_at IS '任务完成时间';


--
-- Name: COLUMN tasks.deadline; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.tasks.deadline IS '计划完成截止时间，超过此时间未完成视为逾期';


--
-- Name: COLUMN tasks.remark; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.tasks.remark IS '备注';


--
-- Name: COLUMN tasks.created_at; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.tasks.created_at IS '记录创建时间';


--
-- Name: tasks_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tasks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tasks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: browser_histories browser_history_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.browser_histories
    ADD CONSTRAINT browser_history_pkey PRIMARY KEY (id);


--
-- Name: browser_history_visits browser_history_visits_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.browser_history_visits
    ADD CONSTRAINT browser_history_visits_pkey PRIMARY KEY (id);


--
-- Name: file_links file_link_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.file_links
    ADD CONSTRAINT file_link_pkey PRIMARY KEY (id);


--
-- Name: task_plan_old pk_task_plan; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task_plan_old
    ADD CONSTRAINT pk_task_plan PRIMARY KEY (id);


--
-- Name: port_forwarding port_forwarding_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.port_forwarding
    ADD CONSTRAINT port_forwarding_pkey PRIMARY KEY (id);


--
-- Name: project_groups project_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_groups
    ADD CONSTRAINT project_groups_pkey PRIMARY KEY (id);


--
-- Name: projects projects_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT projects_pkey PRIMARY KEY (id);


--
-- Name: quick_edit_files quick_edit_files_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quick_edit_files
    ADD CONSTRAINT quick_edit_files_pkey PRIMARY KEY (id);


--
-- Name: quick_edit_snapshots quick_edit_snapshots_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quick_edit_snapshots
    ADD CONSTRAINT quick_edit_snapshots_pkey PRIMARY KEY (id);


--
-- Name: task_plans task_plans_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task_plans
    ADD CONSTRAINT task_plans_pkey PRIMARY KEY (id);


--
-- Name: tasks tasks_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT tasks_pkey PRIMARY KEY (id);


--
-- Name: task_plan_old uni_code; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task_plan_old
    ADD CONSTRAINT uni_code UNIQUE (code);


--
-- Name: idx_history_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_history_id ON public.browser_history_visits USING btree (history_id);


--
-- Name: idx_pid; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_pid ON public.task_plan_old USING btree (pid);


--
-- Name: idx_project_groups_path; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX idx_project_groups_path ON public.project_groups USING btree (absolute_path);


--
-- Name: idx_project_groups_recycle; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX idx_project_groups_recycle ON public.project_groups USING btree (is_recycle_bin) WHERE (is_recycle_bin = true);


--
-- Name: idx_projects_abs_path; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX idx_projects_abs_path ON public.projects USING btree (absolute_path) WHERE (is_deleted = false);


--
-- Name: idx_projects_group; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_projects_group ON public.projects USING btree (group_id);


--
-- Name: idx_quick_edit_files_path; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX idx_quick_edit_files_path ON public.quick_edit_files USING btree (file_path);


--
-- Name: idx_quick_edit_snapshots_file_time; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_quick_edit_snapshots_file_time ON public.quick_edit_snapshots USING btree (file_id, created_at);


--
-- Name: idx_status_type; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_status_type ON public.task_plan_old USING btree (status, type);


--
-- Name: idx_task_plans_parent; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_task_plans_parent ON public.task_plans USING btree (parent_id);


--
-- Name: idx_task_plans_type_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_task_plans_type_status ON public.task_plans USING btree (plan_type, status);


--
-- Name: idx_tasks_plan; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_tasks_plan ON public.tasks USING btree (plan_id);


--
-- Name: idx_tasks_queue; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_tasks_queue ON public.tasks USING btree (status, deadline);


--
-- Name: projects projects_group_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT projects_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.project_groups(id) ON DELETE RESTRICT;


--
-- Name: quick_edit_snapshots quick_edit_snapshots_file_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quick_edit_snapshots
    ADD CONSTRAINT quick_edit_snapshots_file_id_fkey FOREIGN KEY (file_id) REFERENCES public.quick_edit_files(id) ON DELETE CASCADE;


--
-- Name: task_plans task_plans_parent_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task_plans
    ADD CONSTRAINT task_plans_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.task_plans(id) ON DELETE SET NULL;


--
-- Name: tasks tasks_plan_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT tasks_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.task_plans(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict 7zkAqOBN5nWzKZNku8wrVuaRht8krfICyEZoTfxQscsEcEhcesyqtKlfxDoyxRW

