-- DROP TABLE IF EXISTS browser_history_visits;
-- DROP TABLE IF EXISTS browser_histories;
-- DROP TABLE IF EXISTS port_forwarding;
-- DROP TABLE IF EXISTS task_plans;
-- DROP TABLE IF EXISTS tasks;
-- DROP TABLE IF EXISTS file_links;


CREATE TABLE IF NOT EXISTS browser_histories
(
    id              VARCHAR PRIMARY KEY,
    last_visit_time DOUBLE PRECISION NOT NULL,
    title           TEXT,
    type_count      INTEGER DEFAULT 0,
    url             TEXT,
    visit_count     INTEGER DEFAULT 0,
    is_deleted      BOOLEAN DEFAULT FALSE
);


CREATE TABLE IF NOT EXISTS browser_history_visits
(
    id                 VARCHAR PRIMARY KEY,
    history_id         VARCHAR NOT NULL,
    is_local           BOOLEAN,
    referring_visit_id VARCHAR,
    transition         TEXT,
    visit_id           VARCHAR,
    visit_time         DOUBLE PRECISION,
    is_deleted         BOOLEAN DEFAULT FALSE
    -- 建立外键约束
    -- CONSTRAINT fk_browser_history FOREIGN KEY (history_id) REFERENCES browser_history (id)
);

-- 添加索引以提高查询性能
CREATE INDEX idx_history_id ON browser_history_visits (history_id);



CREATE TABLE IF NOT EXISTS port_forwarding
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR,
    port        INTEGER,
    target_host VARCHAR,
    target_port INTEGER,
    status      BOOLEAN DEFAULT FALSE,
    is_deleted  BOOLEAN DEFAULT FALSE
);


-- 任务管理
-- 任务计划表
CREATE TABLE IF NOT EXISTS task_plans
(
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id           INTEGER      REFERENCES task_plans (id) ON DELETE SET NULL,
    name                VARCHAR(500) NOT NULL,
    status              VARCHAR(20)  NOT NULL DEFAULT 'created',
    plan_type           VARCHAR(20)  NOT NULL DEFAULT 'todo',
    cron_expr           VARCHAR(100),
    order_num           INTEGER               DEFAULT 0,
    priority            INTEGER               DEFAULT 5,
    fsrs_stability      DOUBLE PRECISION      DEFAULT 0,
    fsrs_difficulty     DOUBLE PRECISION      DEFAULT 0,
    fsrs_reps           INTEGER               DEFAULT 0,
    fsrs_lapses         INTEGER               DEFAULT 0,
    fsrs_state          INTEGER               DEFAULT 0,
    fsrs_learning_steps INTEGER               DEFAULT 0,
    fsrs_last_review_at TIMESTAMPTZ,
    content_size        INTEGER               DEFAULT 0,
    remark              TEXT,
    link                TEXT,
    created_at          TIMESTAMPTZ           DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ           DEFAULT CURRENT_TIMESTAMP,
    is_deleted          BOOLEAN               DEFAULT FALSE
);

COMMENT ON TABLE task_plans IS '任务计划表';
COMMENT ON COLUMN task_plans.id IS '任务计划唯一标识';
COMMENT ON COLUMN task_plans.parent_id IS '父级任务计划ID，用于树形目录结构。NULL 表示顶级目录';
COMMENT ON COLUMN task_plans.name IS '任务计划名称';
COMMENT ON COLUMN task_plans.status IS '任务计划状态: created(已创建) / started(已开始) / completed(已完成) / archived(已归档)';
COMMENT ON COLUMN task_plans.plan_type IS '任务类型: todo(待办任务) / cron(周期重复任务) / interval(间隔任务)';
COMMENT ON COLUMN task_plans.cron_expr IS 'cron: cron 表达式，plan_type=cron 时必填';
COMMENT ON COLUMN task_plans.fsrs_stability IS 'fsrs: 记忆稳定性，plan_type=interval 时使用';
COMMENT ON COLUMN task_plans.fsrs_difficulty IS 'fsrs: 卡片难度，plan_type=interval 时使用';
COMMENT ON COLUMN task_plans.fsrs_reps IS 'fsrs: 复习次数，plan_type=interval 时使用';
COMMENT ON COLUMN task_plans.fsrs_lapses IS 'fsrs: 遗忘次数，plan_type=interval 时使用';
COMMENT ON COLUMN task_plans.fsrs_state IS 'fsrs: 卡片学习状态，0=Learning 1=Reviewing 2=Relearning，plan_type=interval 时使用';
COMMENT ON COLUMN task_plans.fsrs_last_review_at IS 'fsrs: 上次复习时间，plan_type=interval 时使用';
COMMENT ON COLUMN task_plans.content_size IS '内容大小/字数统计';
COMMENT ON COLUMN task_plans.remark IS '备注';
COMMENT ON COLUMN task_plans.link IS '关联链接';
COMMENT ON COLUMN task_plans.created_at IS '创建时间';
COMMENT ON COLUMN task_plans.updated_at IS '更新时间';

CREATE INDEX idx_task_plans_parent ON task_plans (parent_id);
CREATE INDEX idx_task_plans_type_status ON task_plans (plan_type, status);

-- 任务表（每次执行的实例记录）
CREATE TABLE IF NOT EXISTS tasks
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id      INTEGER     NOT NULL REFERENCES task_plans (id) ON DELETE CASCADE,
    status       VARCHAR(20) NOT NULL DEFAULT 'active',
    priority     INTEGER              DEFAULT 5,
    started_at   TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    deadline     TIMESTAMPTZ,
    remark       TEXT,
    created_at   TIMESTAMPTZ          DEFAULT CURRENT_TIMESTAMP,
    is_deleted   BOOLEAN              DEFAULT FALSE
);

COMMENT ON TABLE tasks IS '任务表（每次执行的实例记录）';
COMMENT ON COLUMN tasks.id IS '任务唯一标识';
COMMENT ON COLUMN tasks.plan_id IS '所属任务计划ID';
COMMENT ON COLUMN tasks.status IS '任务状态: active(已开始/待处理) / done(已完成)';
COMMENT ON COLUMN tasks.started_at IS '任务开始时间（cron/间隔任务的计算时间，待办任务为创建时间）';
COMMENT ON COLUMN tasks.completed_at IS '任务完成时间';
COMMENT ON COLUMN tasks.deadline IS '计划完成截止时间，超过此时间未完成视为逾期';
COMMENT ON COLUMN tasks.remark IS '备注';
COMMENT ON COLUMN tasks.created_at IS '记录创建时间';

CREATE INDEX idx_tasks_queue ON tasks (status, deadline);
CREATE INDEX idx_tasks_plan ON tasks (plan_id);

-- 文件连接表
CREATE TABLE file_links
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_path VARCHAR NOT NULL,
    target_path VARCHAR NOT NULL,
    status      BOOLEAN DEFAULT FALSE,
    remark      TEXT,
    is_deleted  BOOLEAN DEFAULT FALSE
);

-- 快速编辑文件表（被管控的可快速编辑文件列表）
CREATE TABLE quick_edit_files
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR,
    file_path  VARCHAR NOT NULL,
    remark     TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    is_deleted BOOLEAN     DEFAULT FALSE
);

CREATE UNIQUE INDEX idx_quick_edit_files_path ON quick_edit_files (file_path);

-- 快速编辑文件内容历史快照表（每次文件写入成功后记录一条快照）
CREATE TABLE quick_edit_snapshots
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id    INTEGER NOT NULL REFERENCES quick_edit_files (id) ON DELETE CASCADE,
    content    TEXT    NOT NULL,
    size_bytes INTEGER,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    is_deleted BOOLEAN     DEFAULT FALSE
);

CREATE INDEX idx_quick_edit_snapshots_file_time ON quick_edit_snapshots (file_id, created_at);


-- 本地项目文件夹管理
-- 项目组表
CREATE TABLE IF NOT EXISTS project_groups
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(200) NOT NULL,
    order_num     INTEGER               DEFAULT 0,
    absolute_path VARCHAR       NOT NULL,
    remark        TEXT,
    created_at    TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    is_deleted    BOOLEAN     DEFAULT FALSE
);

COMMENT ON TABLE project_groups IS '项目组表';
COMMENT ON COLUMN project_groups.id IS '项目组唯一标识';
COMMENT ON COLUMN project_groups.name IS '项目组名称';
COMMENT ON COLUMN project_groups.order_num IS '排序序号，越小越靠前';
COMMENT ON COLUMN project_groups.absolute_path IS '项目组根目录绝对路径，其下项目通过相对路径定位';
COMMENT ON COLUMN project_groups.remark IS '备注';
COMMENT ON COLUMN project_groups.created_at IS '创建时间';
COMMENT ON COLUMN project_groups.updated_at IS '更新时间';

CREATE UNIQUE INDEX idx_project_groups_path ON project_groups (absolute_path);


-- 项目表
-- 项目绝对路径由所属项目组的绝对路径与相对路径组合得到：
--   absolute_path = project_groups.absolute_path + relative_path
CREATE TABLE IF NOT EXISTS projects
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id         INTEGER      NOT NULL REFERENCES project_groups (id) ON DELETE RESTRICT,
    name             VARCHAR(500) NOT NULL,
    absolute_path    VARCHAR      NOT NULL,
    relative_path    VARCHAR      NOT NULL DEFAULT '',
    git_url          TEXT,
    remark           TEXT,
    last_accessed_at TIMESTAMPTZ,
    created_at       TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    is_deleted       BOOLEAN     DEFAULT FALSE
);

COMMENT ON TABLE projects IS '项目表';
COMMENT ON COLUMN projects.id IS '项目唯一标识';
COMMENT ON COLUMN projects.group_id IS '所属项目组ID';
COMMENT ON COLUMN projects.name IS '项目名称';
COMMENT ON COLUMN projects.absolute_path IS '项目绝对路径，等于 组绝对路径 + 相对路径';
COMMENT ON COLUMN projects.relative_path IS '相对所属项目组根目录的路径';
COMMENT ON COLUMN projects.git_url IS 'Git 仓库地址';
COMMENT ON COLUMN projects.remark IS '备注';
COMMENT ON COLUMN projects.last_accessed_at IS '上次访问时间';
COMMENT ON COLUMN projects.created_at IS '创建时间';
COMMENT ON COLUMN projects.updated_at IS '更新时间';

-- 部分唯一索引：仅对未删除的项目做唯一约束，软删除记录不参与唯一性校验
CREATE UNIQUE INDEX idx_projects_abs_path ON projects (absolute_path) WHERE is_deleted = FALSE;
CREATE INDEX idx_projects_group ON projects (group_id);
